### ISSUE TITLE
Adding a horizontal line before the footnote content

### ISSUE THREAD

**Issue by agmarrugo** [gettalong/kramdown#14]
I'd really like to separate the footnote content with a horizontal line. I've seen that  in

```
# File lib/kramdown/converter/html.rb, line 397
def footnote_content
```

The footnote content is generated as 

```
"<div class=\"footnotes\">\n#{convert(ol, 2)}</div>\n"
```

I think it would be better to add a `</hr>` so that the footnotes are separated from the main content.

**Comment by CarterPape** [comment]
@gettalong, I definitely agree with @agmarrugo that this should be done. [Daring Fireball](https://daringfireball.net/2018/05/duplex_booked_restaurant)'s CMS does this automatically somehow, and I think it's a good illustration of why: borders (especially on block elements) are limited in their role as dividers compared to `<hr />`s, which exist for the purpose of being what is asked for here: a logical, horizontal, customizable divider between the `.footnotes` element and the rest of the text. Asking developers to use CSS to define a border in this way is limiting.

I'd like to see this issue reopened, but I'd also like to hear a compelling reason not to if such is a reason exists.

**Comment by gettalong** [comment]
@CarterPape The `<hr />` serves no real purpose in the output except visually offsetting the footnotes.

If you really need to change the output to your tastes, just subclass the HTML converter. This would be the best way.

Otherwise see https://kramdown.gettalong.org/converter/html.html#footnotes for a way to set the location of the footnotes and use the [horizontal rule syntax](https://kramdown.gettalong.org/syntax.html#horizontal-rules) to insert the rule.

**Comment by agmarrugo** [comment]
@CarterPape I ended up doing it via CSS styling. I still have an octopress (Jekyll) blog that uses kramdown. I've been meaning to change to something else, but haven't had the time. What do you think?

```css
div.footnotes {
	font-size: 0.8em;
/*   padding-left: $pad-min;*/
	hr {
/*	padding-left: 0px;*/
    	border: none;
    	background-color: #ccc;
    	color: #ccc;
    	height: 1px;
	}
	ol {
		padding: 0px 5px 5px 30px;
	}
}
```
