### ISSUE TITLE
Fenced code blocks not working with Rouge syntax highlighting

### ISSUE THREAD

**Issue by jasonszhao** [gettalong/kramdown#271]
In Jekyll, if I use `~~~` syntax, my code isn't highlighted, but if I use the `{% highlight %}` syntax, it works properly. (Using backtick syntax, kramdown doesn't even detect it as code.)

My **config.yml** 

``` yml
markdown:             kramdown
kramdown: 
  syntax_highlighter: rouge

```
My setup works with Redcarpet + Pygments, so I don't think this is a problem with Jekyll.
