### ISSUE TITLE
Incorrect highlight on single fenced code

### ISSUE THREAD

**Issue by alexconst** [gettalong/kramdown#332]
This issue was originally posted at https://github.com/jekyll/jekyll/issues/4627
But the cause of the problem was determined to be kramdown. And persists in v1.10

**tl,dr:**

Settings:

```
markdown: kramdown
kramdown:
    input: GFM 
    hard_wrap: false
    toc_levels: 1..6
    syntax_highlighter: rouge
```

What did you expect to see?
https://camo.githubusercontent.com/c37ca8a1c7672aef97dec5d3f76071f9d33fe933/68747470733a2f2f692e696d6775722e636f6d2f5677417a7466692e706e67

What did you see instead?
https://camo.githubusercontent.com/62881aaceba4594401850add8fee1530a5001ab2/68747470733a2f2f692e696d6775722e636f6d2f7572384a654c732e706e67
