### ISSUE TITLE
Kramdown not able to disable syntax highlighting in inline code spans?

### ISSUE THREAD

**Issue by kwotsin** [gettalong/kramdown#409]
I can't seem to disable syntax highlighting on the inline code spans (like `this`) on my posts when I write the following in my `_config.yml` file:

```yaml
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: False
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: false
```

I am currently hosting on GitHub pages. Is there a way to change the highlighting to something that is found right in this post on GitHub (like `this is an inline code span`)? Am I writing the yaml code correctly for Kramdown?

Currently my inline code span looks like this:

http://i.imgur.com/acrZBLs.png

**Comment by gettalong** [comment]
If you use the correct options, it will work (see https://kramdown.gettalong.org/syntax_highlighter/rouge.html): `{syntax_highlighter_opts: {span: {disable: true}}}`

**Comment by kwotsin** [comment]
I have disabled according to your suggestion by writing the code like this:

```
kramdown:
  input: GFM
  hard_wrap: False
  syntax_highlighter: rouge
  {syntax_highlighter_opts: {span: {disable: true}}}
```
However, the highlighting seems to be continuing. Am I writing the code correctly?
