### ISSUE TITLE
Adding a CSS Class to Code "Spans"

### ISSUE THREAD

**Issue by ryanjwilke** [gettalong/kramdown#464]
I've been doing a little digging on whether or not it's possible to add a CSS class to the inline `code`, but it would appear that it might not be possible currently as a result of [this line](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter/rouge.rb#L61) which forces the `wrap` option to be set to `false`, which in turn makes Rouge ignore the `css_class` option. Is there maybe something I'm missing? I would love to be able to get a class applied to the inline code spans.

Here's what my config looks like:
```
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    block:
      css: class
      wrap: true
      disable: false
      css_class: 'code-block'
    span:
      css: class
      wrap: true
      disable: false
      css_class: 'code-inline'
```

The `block` section works just fine, but the `span` section gets ignored.

Thanks in advance for your help!
