### ISSUE TITLE
Internal links in footnotes

### ISSUE THREAD

**Issue by xuhcc** [gettalong/kramdown#623]
Hi,

I'm using Github Pages service to generate a static website from a collection of markdown files.
Links in footnotes are not working as expected. They are rendered as links to markdown files, instead of links to html files.

**test1.md**

```markdown
TEST[^1].

[test2](test2.md).             # Rendered as <a href="/test2.html">test2</a>

[^1]: [test2](test2.md).       # Rendered as <a href="test2.md">test2</a>
```

**test2.md**
```markdown
TEST
```

**_config.yml**:

```yaml
...
kramdown:
  gfm_quirks: [paragraph_end, no_auto_typographic]
...
```
