### ISSUE TITLE
Incorrect interpretation with line break in SHELL

### ISSUE THREAD

**Issue by Merikanto** [gettalong/kramdown#628]
This is my config:

```
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: shell
    hard_wrap: true
    css_class: 'syntax'
```

And after I set the default language to SHELL, there're problems with line breaks: **It doesn't interpret RETURN / ENTER as link break**. 

For instance, normally a shell script should look like this:

```
for n in {0..4}; do
	if [[ $n == 2 ]]; then
		continue	
	fi
	echo $n
done
```

However, it looks like this in kramdown's renderer:

```
for n in {0..4}; do if [[ $n == 2 ]]; then continue  fi  echo 
$n done
```

I checked my other settings, and once I changed the default lang to almost ANY OTHER language, this problem disappears. Bu every time with SHELL, codes got all messed up.

Thanks!
