### ISSUE TITLE
github+kramdown+rouge+escape+mathjax

### ISSUE THREAD

**Issue by makslevental** [gettalong/kramdown#701]
I'm trying to use MathJax inside a code block that's being highlighted using rouge (with jekyll on github). Rouge let's you escape styling by using their [escape lexer](https://github.com/rouge-ruby/rouge/pull/1152) and `<! !>`, which is activated by [passing](https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/cli.rb#L202) `--escape` when running rouge by hand. I tried passing `escape: true` in my `_config.yml` for jekyll

```yaml
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    escape: true
```

but alas it doesn't work

![image](https://user-images.githubusercontent.com/5657668/106831187-18d81600-6655-11eb-8445-629701250402.png)

note that I do have the correct config set for my MathJax object (i.e. I don't have `<code>` or `<pre>` in `skipHtmlTags`) since 

```
def mathjax_fn():
    $\gamma$ = 5+5
    return 5* $\gamma$
```

renders to

![image](https://user-images.githubusercontent.com/5657668/106831253-34dbb780-6655-11eb-8b8b-293ddace15c5.png)

Am I doing something wrong or is this not supported?
