### ISSUE TITLE
Kramdown option in Jekyll fail

### ISSUE THREAD

**Issue by dungxibo123** [gettalong/kramdown#742]
Consider a simple markdown case
```
# 4. Loi ket
Lorem lorem lorem
```
My rendered output is
```html
<h1 id="4-loi-ket">4. Loi ket</h1>
<p>Lorem lorem lorem</p>
```
But I want it turned into
```html
<section id="4-loi-ket">
<h1>.....
....
....
</section>
```
Following the document here
![image](https://user-images.githubusercontent.com/41417288/147171543-1a0226b1-f835-4613-a8ec-c1aa261deb0a.png)
I set my `_config.yml` file into
```
markdown: kramdown
kramdown:
  auto-id-stripping: true
  highlighter: rouge
  input: GFM
```
So I thought my desire content will be wrapped by the `section` tag, but the rendered html did not change. Am I misunderstanding the document content or I need set other option to achieve desire output.

Thanks
