### ISSUE TITLE
add langauge html prop to generated code from highlighter-rouge

### ISSUE THREAD

**Issue by godalming123** [gettalong/kramdown#756]
recently saw [Phisch's blog markdown demo](https://phisch.github.io/blog/demo) and wanted to implement the langauge text in the top right corner of code blocks on my own website this is done by using a `langaunge` attribute of the `.highlighter-rouge` element which is added with js instead of using js would it be possible to generate this automatically so we can add this with just css. EG generated code:
```html
<div class="language-kotlin highlighter-rouge" language="kotlin">...</div>
```
and then custom css
```css
.highlighter-rouge::before {
  content: attr(language);
  background: $header-color;
  width: 100%;
  padding: 3px;
}
```
