### ISSUE TITLE
Jekyll kramdown: How to disable generating styles in tables?

### ISSUE THREAD

**Issue by yagarea** [gettalong/kramdown#796]
I have markdown file with standard markdown table:

```md
| AAA | BBB |
|:---:|:---:|
| 1   | 2   |
| 3   | 4   |
```

Jekyll renders it fine but adds `text-align: center;` in to style of `td`:

```html
<table>
	<thead>
		<tr>
			<th style="text-align: center">AAA</th>
			<th style="text-align: center">BBB</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td style="text-align: center">1</td>
			<td style="text-align: center">2</td>
		</tr>
		<tr>
			<td style="text-align: center">3</td>
			<td style="text-align: center">4</td>
		</tr>
	</tbody>
</table>
```

how to disable this so jekyll does not add any styles to table elements ?  
Thank you for help

---

I have **Jekyll 4.3.2** and this is contents of my `_config.yml`:
```yml
highlighter: rouge
markdown: kramdown
    style: :compressed
permalink: "/:title/"
slugify: "pretty"
```
